#!/bin/sh
# Test driver for tst-dso-ordering-all4-30, generated by dso-ordering-test.py
common_objpfx=$1
test_wrapper_env=$2
run_program_env=$3
library_path=$(echo $4)
something_failed=false
${test_wrapper_env} ${run_program_env} GLIBC_TUNABLES=glibc.rtld.dynamic_sort=1 \
${common_objpfx}support/test-run-command \
${common_objpfx}elf/ld.so \
--library-path $library_path:${common_objpfx}elf/tst-dso-ordering-all4-30-dir:${common_objpfx}elf:${common_objpfx}.:${common_objpfx}dlfcn \
${common_objpfx}elf/tst-dso-ordering-all4-30-dir/tst-dso-ordering-all4-30 > \
  ${common_objpfx}elf/tst-dso-ordering-all4-30-dir/tst-dso-ordering-all4-30-glibc.rtld.dynamic_sort_1.output
if [ $? -ne 0 ]; then
  echo 'FAIL: tst-dso-ordering-all4-30(GLIBC_TUNABLES=glibc.rtld.dynamic_sort=1) execution test'
  something_failed=true
else
  diff -wu ${common_objpfx}elf/tst-dso-ordering-all4-30-dir/tst-dso-ordering-all4-30-glibc.rtld.dynamic_sort_1.output \
           ${common_objpfx}elf/dso-sort-tests-src/tst-dso-ordering-all4-30.exp
  if [ $? -ne 0 ]; then
    echo 'FAIL: tst-dso-ordering-all4-30(GLIBC_TUNABLES=glibc.rtld.dynamic_sort=1) expected output comparison'
    something_failed=true
  fi
fi
${test_wrapper_env} ${run_program_env} GLIBC_TUNABLES=glibc.rtld.dynamic_sort=2 \
${common_objpfx}support/test-run-command \
${common_objpfx}elf/ld.so \
--library-path $library_path:${common_objpfx}elf/tst-dso-ordering-all4-30-dir:${common_objpfx}elf:${common_objpfx}.:${common_objpfx}dlfcn \
${common_objpfx}elf/tst-dso-ordering-all4-30-dir/tst-dso-ordering-all4-30 > \
  ${common_objpfx}elf/tst-dso-ordering-all4-30-dir/tst-dso-ordering-all4-30-glibc.rtld.dynamic_sort_2.output
if [ $? -ne 0 ]; then
  echo 'FAIL: tst-dso-ordering-all4-30(GLIBC_TUNABLES=glibc.rtld.dynamic_sort=2) execution test'
  something_failed=true
else
  diff -wu ${common_objpfx}elf/tst-dso-ordering-all4-30-dir/tst-dso-ordering-all4-30-glibc.rtld.dynamic_sort_2.output \
           ${common_objpfx}elf/dso-sort-tests-src/tst-dso-ordering-all4-30.exp
  if [ $? -ne 0 ]; then
    echo 'FAIL: tst-dso-ordering-all4-30(GLIBC_TUNABLES=glibc.rtld.dynamic_sort=2) expected output comparison'
    something_failed=true
  fi
fi
if $something_failed; then
  exit 1
else
  echo 'PASS: all tests for tst-dso-ordering-all4-30 succeeded'
  exit 0
fi
